### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by CziSKY** [rowscript/rowscript.github.io#2]
Since the framework `docusaurus` used on the RowScript website has good i18n support, given RowScript's target group of users, I think i18n support is necessary!

**Comment by CziSKY** [comment]
I can be the Chinese maintainer; if you don't mind, I'll pull a PR in a couple of days. Any suggestions? @anqurvanillapy

**Comment by CziSKY** [comment]
Anqur recognized my work in Private Chat on QQ and made a few requests:

0. Overturn the current English version to the first support for the Chinese version.
1. Some terms about PL features, such as "traits", are to be used directly in English without translation.

**Comment by anqur** [comment]
Thanks for your sincere support here! Quite busy these weeks and soon let's head down to start a brand new documentation of RowScript!

**Comment by CziSKY** [comment]
I apologize for the delay in implementing this feature, as some personal matters arose in my real life. I encountered some issues with understanding certain modules of Docusaurus, such as the locale handling in single-domain-deployment. However, those issues have now been resolved, and I will submit a PR with the current version either this Saturday or Sunday.
